<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="4" time="109.060" timestamp="2025-09-22T04:33:44.251616+00:00" hostname="codespaces-7d04bd"><testcase classname="test_health_check.TestHealthCheck" name="test_streamlit_app_loads[chromium]" time="5.363" /><testcase classname="test_health_check.TestHealthCheck" name="test_login_form_exists[chromium]" time="5.598" /><testcase classname="test_health_check.TestHealthCheck" name="test_admin_login_works[chromium]" time="22.548" /><testcase classname="test_health_check.TestHealthCheck" name="test_main_navigation_tabs[chromium]" time="75.510"><error message="failed on setup with &quot;Exception: Login appears to have failed. Expected to find main app content after login.&quot;">conftest.py:132: in authenticated_admin_page
    login_as_admin(page)
conftest.py:208: in login_as_admin
    raise Exception("Login appears to have failed. Expected to find main app content after login.")
E   Exception: Login appears to have failed. Expected to find main app content after login.</error></testcase></testsuite></testsuites>